### ISSUE TITLE
App crashed in Android 7 devices

### ISSUE THREAD

**Issue by kenma9123** [facebook/react-native#14346]
Description

I have been using react since, I published my app to playstore. So I got reports from the ANR/Crashes tab.  This happen specifically on android 7 devices. and even on emulator.

Google play sometimes call it "tgkill" and have trace like this. I have so many crashes like 50 and up.

```
backtrace:
  native: pc 000000000004b4a0  /system/lib/libc.so (tgkill+12)
  native: pc 0000000000048ba3  /system/lib/libc.so (pthread_kill+34)
  native: pc 000000000001e1b9  /system/lib/libc.so (raise+10)
  native: pc 00000000000197a5  /system/lib/libc.so (__libc_android_abort+34)
  native: pc 0000000000017540  /system/lib/libc.so (abort+4)
  native: pc 000000000000cce1  /system/lib/libcutils.so (__android_log_assert+112)
  native: pc 000000000003d783  /system/lib/libhwui.so
  native: pc 0000000000027583  /system/lib/libhwui.so
  native: pc 0000000000025b19  /system/lib/libhwui.so
  native: pc 00000000000285f9  /system/lib/libhwui.so
  native: pc 0000000000028ec3  /system/lib/libhwui.so
  native: pc 0000000000029f19  /system/lib/libhwui.so (_ZN7android10uirenderer12renderthread12RenderThread10threadLoopEv+80)
  native: pc 000000000000e6ab  /system/lib/libutils.so (_ZN7android6Thread11_threadLoopEPv+178)
  native: pc 0000000000069a39  /system/lib/libandroid_runtime.so (_ZN7android14AndroidRuntime15javaThreadShellEPv+80)
  native: pc 0000000000048677  /system/lib/libc.so (_ZL15__pthread_startPv+22)
  native: pc 000000000001a411  /system/lib/libc.so (__start_thread+6)
```

It's working as expected on Android 6 and 5 devices but not with 7 really. So I'm not sure what's happening inside.

react-native 0.43
react 16.0.0-alpha.6
Android emulator android 7.0
Real phone android : 7
