### ISSUE TITLE
Compile Warnings on iOS and Travis iOS

### ISSUE THREAD

**Issue by ulfgebhardt** [facebook/react-native#17151]
<img width="635" alt="bildschirmfoto_2017-12-11_um_16 56 56" src="https://user-images.githubusercontent.com/1238238/33840170-71e42bea-de94-11e7-857f-852f21433781.png">

### Is this a bug report?

Yes

### Have you read the [Contributing Guidelines](https://facebook.github.io/react-native/docs/contributing.html)?

No

### Environment

> react-native info

```
Environment:
  OS: macOS High Sierra 10.13.1
  Node: 8.9.2
  Yarn: 1.3.2
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 9.2 Build version 9C40b
  Android Studio: 3.0 AI-171.4443003

Packages: (wanted => installed)
  react: 16.0.0 => 16.0.0
  react-native: 0.51.0 => 0.51.0
```
Rel: https://github.com/demokratie-live/democracy-client/blob/master/package.json
Rel: https://github.com/demokratie-live/democracy-client/blob/master/yarn.lock

> And .travis.yml

```
# ios
-   if: branch =~ ^master AND NOT type =~ ^pull_request # this line exists because Travis Mac Maschines are rare and slow
    os: osx
    osx_image: xcode9
    language: objective-c
    install:
        - nvm install 8
        - npm install -g yarn
        - yarn --version
        - yarn install
    xcode_project: ios/democracyclient.xcodeproj
    xcode_scheme: ios/democracyclientTests
    script:
        - yarn build:ios
```
Rel: https://github.com/demokratie-live/democracy-client/blob/master/.travis.yml

### Steps to Reproduce

1.a Compile with 
> cd ios && xcodebuild -quiet -scheme democracyclient -configuration Release -sdk iphonesimulator

1.b Compile [democracy-client](https://github.com/demokratie-live/democracy-client) with "yarn build:ios"
2. Warnings are generated. Espec for unused Parameters. See [here](https://travis-ci.org/demokratie-live/democracy-client/jobs/314808611)
3. ...
4. Profit

### Expected Behavior

No warnings should be generated.
Warnings should not be suppressed; Warnings should be fixed.

### Actual Behavior

Warnings are generated - alot - see [here](https://travis-ci.org/demokratie-live/democracy-client/jobs/314808611)

### Reproducible Demo

- [Project democracy-client](https://github.com/demokratie-live/democracy-client)
- [Travis democracy-client](https://travis-ci.org/demokratie-live/democracy-client)
- [Travis build of Master including the warnings](https://travis-ci.org/demokratie-live/democracy-client/jobs/31480861)

### Other Solutions

- Provide a better build command
- Point out Configuration Problems
