### ISSUE TITLE
Travis error on react-native IOS Release scheme

### ISSUE THREAD

**Issue by harrydema** [facebook/react-native#20656]
## Environment
React Native Environment Info:
    System:
      OS: macOS Sierra 10.12.6
      CPU: x64 Intel(R) Core(TM) i5-2435M CPU @ 2.40GHz
      Memory: 29.20 MB / 8.00 GB
      Shell: 5.2 - /bin/zsh
    Binaries:
      Node: 9.0.0 - ~/.nvm/versions/node/v9.0.0/bin/node
      Yarn: 1.9.2 - /usr/local/bin/yarn
      npm: 5.5.1 - ~/.nvm/versions/node/v9.0.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 11.2, macOS 10.13, tvOS 11.2, watchOS 4.2
      Android SDK:
        Build Tools: 23.0.1, 23.0.3, 25.0.1, 25.0.2, 25.0.3, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.2, 27.0.3
        API Levels: 23, 25, 26, 27
    IDEs:
      Android Studio: 3.1 AI-173.4819257
      Xcode: 9.2/9C40b - /usr/bin/xcodebuild
    npmPackages:
      react: 16.4.1 => 16.4.1 
      react-native: 0.56.0 => 0.56.0 
    npmGlobalPackages:
      create-react-native-app: 1.0.0
      react-native-cli: 2.0.1
      react-native-git-upgrade: 0.2.7

## Description
When i build ios release scheme locally i get no errors, but when i build on travis the release scheme i get this error under Running script 'Bundle React Native code and images':

File /Users/travis/Library/Developer/Xcode/DerivedData/TestApp-bktrthrvpvtbhdcrrzrzfekixdcy/Build/Products/Release-iphonesimulator/TestApp.app/main.jsbundle does not exist. This must be a bug with

I checked that when i run it locally the main.jsbundle is copied inside this folder but on travis this file is not copied although before building i run: react-native bundle --platform ios --dev false --entry-file index.js --bundle-output ios/main.jsbundle

I am using react-native v0.56

## Reproducible Demo
This is my .travis.yml configuration:
```
- language: objective-c
      sudo: required
      xcode_project: ios/TestApp.xcworkspace
      xcode_scheme: ios/Release
      node_js: false
      env:
        - TEST='IOS RELEASE BUILD'
      before_install:
        - nvm install 9.10.0
      install:
        - brew install yarn
        - yarn install
        - npm install -g react-native-cli
      script:
        - react-native bundle --platform ios --dev false --entry-file index.js --bundle-output ios/main.jsbundle
        - cd ios
        - xcodebuild -workspace TestApp.xcworkspace -scheme Release -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c; exit ${PIPESTATUS[0]}
```
