### ISSUE TITLE
The unclosed border is serrated on Android.

### ISSUE THREAD

**Issue by panda912** [facebook/react-native#29406]
Please provide all the information requested. Issues that do not follow this format are likely to stall.

## Description
The unclosed border is serrated on Android.
![unclosed](https://user-images.githubusercontent.com/5298742/87774896-ce797e00-c857-11ea-90b6-2691cf83d514.png)

## React Native version:
System:
    OS: Windows 10 10.0.18362
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
    Memory: 5.06 GB / 15.89 GB
  Binaries:
    Node: 12.18.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.5.1 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.5 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Version  3.6.0.0 AI-192.7142.36.36.6308749
  Languages:
    Java: 1.8.0_201 - C:\Program Files\Java\jdk1.8.0_201\bin\javac.EXE
    Python: 3.8.3 - C:\Python38\python.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.13.1 => 16.13.1
    react-native: 0.63.1 => 0.63.1
  npmGlobalPackages:
    *react-native*: Not Found

## Steps To Reproduce
Provide a detailed list of steps that reproduce the issue.
```css
  style: {
    width: 100,
    height: 45,
    borderColor: "#999999",
    borderTopLeftRadius: 60,
    borderBottomLeftRadius: 60,
    borderLeftWidth: 2,
    borderTopWidth: 2,
    borderBottomWidth: 2
  }
```

## Expected Results
no serrations.

## Snack, code example, screenshot, or link to a repository:
N/A
