### ISSUE TITLE
[0.59.10] textShadow

### ISSUE THREAD

**Issue by kdreaming** [facebook/react-native#32568]
### Description

Why the shadow on the right side of the text cannot exceed the text range? help me.

### Version

0.59.10

### Output of `react-native info`

React Native Environment Info:
    System:
      OS: macOS 11.6
      CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 115.41 MB / 16.00 GB
      Shell: 5.8 - /bin/zsh
    Binaries:
      Node: 12.18.3 - ~/.nvm/versions/node/v12.18.3/bin/node
      Yarn: 1.22.10 - ~/.nvm/versions/node/v12.18.3/bin/yarn
      npm: 6.14.6 - ~/.nvm/versions/node/v12.18.3/bin/npm
      Watchman: 20210404.182228.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
      Android SDK:
        API Levels: 19, 23, 25, 26, 27, 28, 30
        Build Tools: 23.0.1, 26.0.3, 27.0.3, 28.0.3, 30.0.2
        System Images: android-19 | ARM EABI v7a, android-25 | Google Play Intel x86 Atom
    IDEs:
      Android Studio: 3.2 AI-181.5540.7.32.5056338
      Xcode: 11.2/11B52 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.3 => 16.6.3 
      react-native: ^0.59.10 => 0.59.10 

### Steps to reproduce

my style:
```css
screenDisplay: {
        position: 'absolute',
        bottom: 10,
        left: 10,
        fontSize: 20,
        color: '#fff',
        opacity: 0.4,
        textShadowOffset: {width: 2, height: 2},
        textShadowRadius: 4,
        shadowOpacity: 0.5,
        textShadowColor: '#000'
    }
```
effect:
![image](https://user-images.githubusercontent.com/24806638/141077417-dacea08c-8003-4da6-9324-7a4346574b0c.png)
