### ISSUE TITLE
When opening/closing the modal, extra keyboard events may be emitted.

### ISSUE THREAD

**Issue by ntdiary** [facebook/react-native#38633]
### Description

This is an issue that happens on IOS.
We want to make sure the keyboard is hidden before opening the modal, so that when closing the modal we can show or continue hiding the keyboard as needed. But these unnecessary keyboard events cause trouble for our other components and page layout ( e.g., the screen flash, because the `KeyboardAvoidingView` component will rely on the keyboard event to update its height).

### React Native Version

0.72.3

### Output of `npx react-native info`

```yaml
System:
  OS: macOS 13.4
  CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
  Memory: 6.11 GB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.15.1
    path: ~/.nvm/versions/node/v16.15.1/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v16.15.1/bin/yarn
  npm:
    version: 8.11.0
    path: ~/.nvm/versions/node/v16.15.1/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/ntdiary/.rvm/gems/ruby-2.7.5/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: 2022.2 AI-222.4459.24.2221.10121639
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: javac 11
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/ntdiary/.rvm/rubies/ruby-2.7.5/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Steps to reproduce

1. Click the input to show the keyboard.
2. Click the `Open Modal` button to open the modal.
3. Click the `Close Modal` button to close the modal.
4. Check the console will print these extra keyboard events, and the durations of all these events are 0.

### Snack, screenshot, or link to a repository

Snack: https://snack.expo.dev/@ntdiary/keyboard-event-after-closing-modal

https://github.com/facebook/react-native/assets/8579651/c11851f3-2aad-4403-b635-ddd5558ef0f7
