### ISSUE TITLE
Missing implementations for URL

### ISSUE THREAD

**Issue by mxplusb** [facebook/react-native#38966]
### Description

While attempting to run the [Azure Speech SDK](https://github.com/microsoft/cognitive-services-speech-sdk-js) on React Native, it fails to make network requests because the native URL class is not fully implemented.

### React Native Version

0.72.3

### Output of `npx react-native info`

```yaml
System:
  OS: macOS 14.0
  CPU: (10) arm64 Apple M1 Pro
  Memory: 647.14 MB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.16.1
    path: ~/.nvm/versions/node/v18.16.1/bin/node
  Yarn:
    version: 3.6.1
    path: ~/.nvm/versions/node/v18.16.1/bin/yarn
  npm:
    version: 9.5.1
    path: ~/.nvm/versions/node/v18.16.1/bin/npm
  Watchman: Not Found
Managers:
  CocoaPods:
    version: 1.12.1
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 22.4
      - iOS 16.4
      - macOS 13.3
      - tvOS 16.4
      - watchOS 9.4
  Android SDK: Not Found
IDEs:
  Android Studio: Giraffe 2022.3.1 Giraffe 2022.3.1
  Xcode:
    version: 14.3.1/14E300c
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.20
    path: /usr/bin/javac
  Ruby:
    version: 2.6.10
    path: /usr/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.3
    wanted: 0.72.3
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: true
iOS:
  hermesEnabled: Not found
  newArchEnabled: Not found
```

### Steps to reproduce

1. Install [`bent`](https://github.com/mikeal/bent) (the underlying network client for Speech SDK).
2. Make network request with credentials

### Snack, screenshot, or link to a repository

Here is the calling code that fails to make a request: https://github.com/mikeal/bent/blob/master/src/browser.js#L34

I know absolutely nothing about the intermediate translations between React Native and the specific platforms, but I would guess `fetch` is what's causing the problem, but ultimately, I'm not sure.
