### ISSUE TITLE
`react-native upgrade` doesn't exist

### ISSUE THREAD

**Issue by globexdesigns** [facebook/react-native#3941]
This page: https://facebook.github.io/react-native/docs/upgrading.html#content mentions that I should run `npm-native upgrade` after installing a new version of react-native.

But `react-native upgrade` says there's no such option:

```
Command `upgrade` unrecognized
Usage: react-native <command>

Commands:
  start: starts the webserver
  install: installs npm react components
  bundle: builds the javascript bundle for offline use
  new-library: generates a native library bridge
  android: generates an Android project for your app
```

`react-native --version` returns `0.1.7`

I'm confused.
