### ISSUE TITLE
FBReactNativeSpec/FBReactNativeSpec.h: No such file or directory (in target 'React-Codegen' from project 'Pods')

### ISSUE THREAD

**Issue by nvacheishvili** [facebook/react-native#44731]
### Description

I have upgraded to latest react native and I am able to build everything fine locally, while CI keeps throwing this error on build:

FBReactNativeSpec/FBReactNativeSpec.h: No such file or directory (in target 'React-Codegen' from project 'Pods') 

** ARCHIVE FAILED **

The following build commands failed:
	Copy /Users/runner/Library/Developer/Xcode/DerivedData/MobileApp-fsljxdyguedfjldkjtihcbwatykp/Build/Intermediates.noindex/ArchiveIntermediates/MobileAppDev/BuildProductsPath/Release-iphoneos/React-Codegen/React_Codegen.framework/Headers/FBReactNativeSpec/FBReactNativeSpec.h /Users/runner/work/MobileApp/MobileApp/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h (in target 'React-Codegen' from project 'Pods')
(1 failure)
ERROR [2024-05-30 20:10:15.14]: Exit status: 65

### Steps to reproduce

N/A

### React Native Version

0.74.1

### Affected Platforms

Runtime - iOS, Build - MacOS

### Areas

Codegen

### Output of `npx react-native info`

```text
System:
  OS: macOS 14.4.1
  CPU: (12) arm64 Apple M2 Max
  Memory: 3.58 GB / 64.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 21.7.1
    path: /opt/homebrew/bin/node
  Yarn:
    version: 3.6.4
    path: /opt/homebrew/bin/yarn
  npm:
    version: 10.5.0
    path: /opt/homebrew/bin/npm
  Watchman:
    version: 2024.01.22.00
    path: /opt/homebrew/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /opt/homebrew/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.5
      - iOS 17.5
      - macOS 14.5
      - tvOS 17.5
      - visionOS 1.2
      - watchOS 10.5
  Android SDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11255304
  Xcode:
    version: 15.4/15F31d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/natavacheishvili/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.1
    wanted: ^0.74.1
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Stacktrace or Logs

```text
N/A
```

### Reproducer

N/A

**Comment by steadev** [comment]
I got same error sometimes.
Reinstall pods worked for me

**Comment by abhaypithadiya** [comment]
I am facing the same issue. Reinstalling Pods didn't work for me.

**Comment by cipolleschi** [comment]
Hi all @nvacheishvili @steadev and @abhaypithadiya!
In 0.74 there has been a breaking change, for which `React-Codegen` has been renamed to `ReactCodegen` to avoid the dance for which static libraries are ok with `React-Codegen` as a name and frameworks needs `React_Codegen` (notice the `-` versus the `_`).

We also changed a little how we run cocoapods, as Codegen now always runs in both architectures.

The error you linked above, which I paste below, means that your app can't find the `FBReactNativeSpec.h` file.

```
FBReactNativeSpec/FBReactNativeSpec.h: No such file or directory (in target 'React-Codegen' from project 'Pods')

** ARCHIVE FAILED **

The following build commands failed:
Copy /Users/runner/Library/Developer/Xcode/DerivedData/MobileApp-fsljxdyguedfjldkjtihcbwatykp/Build/Intermediates.noindex/ArchiveIntermediates/MobileAppDev/BuildProductsPath/Release-iphoneos/React-Codegen/React_Codegen.framework/Headers/FBReactNativeSpec/FBReactNativeSpec.h /Users/runner/work/MobileApp/MobileApp/ios/build/generated/ios/FBReactNativeSpec/FBReactNativeSpec.h (in target 'React-Codegen' from project 'Pods')
(1 failure)
ERROR [2024-05-30 20:10:15.14]: Exit status: 65
```

So, some questions to let you unblock yourselves:

1. From which library the error come from?
2. Are you building with the New Architecture or the Old Architecture?
3. You mentioned that you have the error in CI: are you using a cache, perhaps? Can you try to invalidate it?
4. Can you create a repro using this [template](https://github.com/react-native-community/reproducer-react-native)

--- 

I just tried to archive a new app created with 0.74 and the archive step worked fine.

**Comment by nvacheishvili** [comment]
1. I think error is coming from Firebase library
2. I am using old architecture
3. I have invalidated caches, but still the same issue
4. Reproducing this environment will be super complicated, so unfortunately I cannot but I will give you more details regarding my Podfile and errors below. 

One important thing to mention is that React-Codegen is working just fine on my local setup, and uploading the builds using fastlane to ios is working just fine locally. The CI is the one having issues, but its setup does match my local setup. 

Here's my Podfile

```
# Convert all permission pods into static libraries
pre_install do |installer|
  Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}

  installer.pod_targets.each do |pod|
    if pod.name.eql?('RNPermissions') || pod.name.start_with?('Permission-')
      def pod.build_type;
        # Uncomment the line corresponding to your CocoaPods version
        Pod::BuildType.static_library # >= 1.9
        # Pod::Target::BuildType.static_library # < 1.9
      end
    end
  end
end

$RNFirebaseAsStaticFramework = true

# Override Firebase SDK Version
$FirebaseSDKVersion = '10.25.0'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.4'
install! 'cocoapods', :deterministic_uuids => false

pod 'Firebase', :modular_headers => true
pod 'FirebaseCoreInternal', :modular_headers => true
pod 'GoogleUtilities', :modular_headers => true

production = ENV["PRODUCTION"] == "1"

abstract_target 'operixCommonPods' do
  # we should leave the use frameworks above use_react_native always,
  # otherwise we're going to get multiple commands produce error
  use_frameworks! :linkage => :static
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :production => production,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  def shared_pods
    permissions_path = '../node_modules/react-native-permissions/ios'
    pod 'Permission-Camera', :path => "#{permissions_path}/Camera"
    pod 'Permission-MediaLibrary', :path => "#{permissions_path}/MediaLibrary"
    pod 'Permission-PhotoLibrary', :path => "#{permissions_path}/PhotoLibrary"
    pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'
  end

  target 'MobileAppDev' do
    shared_pods
  end

  target 'MobileAppOperixProd' do
    shared_pods
  end

  target 'MobileAppSageProd' do
      shared_pods
  end

  target 'MobileAppTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
#          config.build_settings['HEADER_SEARCH_PATHS'] ||= '$(inherited) '
#          config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_ROOT)/Headers/Private/React-bridging/react/bridging" '
#          config.build_settings['HEADER_SEARCH_PATHS'] << '"$(PODS_CONFIGURATION_BUILD_DIR)/React-bridging/react_bridging.framework/Headers" '
         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.4'
         config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)', '_LIBCPP_ENABLE_CXX17_REMOVED_UNARY_BINARY_FUNCTION']
         #Needed for Firebase to work correctly
         config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end
  end
end
```


Here's the package.json
```{
  "name": "mobileapp",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest --runInBand --detectOpenHandles --forceExit",
    "test:ci": "jest --maxWorkers=50%",
    "lint": "eslint MobileApp",
    "android:dev": "react-native run-android --mode=developmentdebug",
    "android:dev-release": "react-native run-android --mode=developmentrelease",
    "android:operixprod": "react-native run-android --mode=operixproductiondebug",
    "android:operixprod-release": "react-native run-android --mode=operixproductionrelease",
    "android:sageprod": "react-native run-android --mode=sageproductiondebug",
    "android:sageprod-release": "react-native run-android --mode=sageproductionrelease"
  },
  "dependencies": {
    "@fortawesome/fontawesome-pro": "^6.2.1",
    "@fortawesome/fontawesome-svg-core": "^6.2.0",
    "@fortawesome/pro-duotone-svg-icons": "^6.2.1",
    "@fortawesome/pro-light-svg-icons": "^6.2.1",
    "@fortawesome/pro-regular-svg-icons": "^6.2.1",
    "@fortawesome/pro-solid-svg-icons": "^6.2.1",
    "@fortawesome/pro-thin-svg-icons": "^6.2.1",
    "@fortawesome/react-native-fontawesome": "^0.3.0",
    "@fortawesome/sharp-solid-svg-icons": "^6.2.1",
    "@operix/oql-builder": "^0.0.5",
    "@react-native-async-storage/async-storage": "^1.23.1",
    "@react-native-clipboard/clipboard": "^1.14.1",
    "@react-native-community/datetimepicker": "^8.0.1",
    "@react-native-community/eslint-config": "^3.2.0",
    "@react-native-community/geolocation": "^3.2.1",
    "@react-native-community/netinfo": "^11.3.2",
    "@react-native-cookies/cookies": "^6.2.1",
    "@react-native-firebase/analytics": "^20.0.0",
    "@react-native-firebase/app": "^20.0.0",
    "@react-native-firebase/crashlytics": "^20.0.0",
    "@react-navigation/drawer": "^6.6.14",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/native-stack": "^6.9.25",
    "@react-navigation/stack": "^6.3.29",
    "@reduxjs/toolkit": "^1.8.2",
    "@splitsoftware/splitio-react-native": "^0.6.3",
    "axios": "^0.27.2",
    "crypto-js": "3.1.9-1",
    "lodash.clonedeep": "^4.5.0",
    "moment": "^2.29.4",
    "native-base": "^3.4.28",
    "prop-types": "^15.8.1",
    "react": "18.2.0",
    "react-dom": "^18.2.0",
    "react-native": "^0.74.1",
    "react-native-actions-sheet": "^0.8.10",
    "react-native-android-location-enabler": "^1.2.2",
    "react-native-background-timer": "^2.4.1",
    "react-native-config": "^1.4.6",
    "react-native-device-info": "^11.1.0",
    "react-native-devsettings": "^1.0.5",
    "react-native-document-picker": "^9.2.0",
    "react-native-element-dropdown": "^2.3.0",
    "react-native-file-viewer": "^2.1.5",
    "react-native-fs": "^2.20.0",
    "react-native-gesture-handler": "^2.16.2",
    "react-native-image-crop-picker": "^0.39.0",
    "react-native-image-viewing": "^0.2.2",
    "react-native-linear-gradient": "^2.6.2",
    "react-native-modal-datetime-picker": "^14.0.0",
    "react-native-multitap": "^0.0.5",
    "react-native-offline": "^6.0.0",
    "react-native-permissions": "^3.6.1",
    "react-native-reanimated": "^3.11.0",
    "react-native-safe-area-context": "^4.10.1",
    "react-native-screens": "^3.31.1",
    "react-native-signature-capture": "^0.4.12",
    "react-native-svg": "^15.3.0",
    "react-native-uuid": "^2.0.1",
    "react-native-webview": "^13.10.2",
    "react-redux": "^8.0.2",
    "redux": "^4.2.0",
    "redux-logger": "^3.0.6",
    "redux-persist": "^6.0.0",
    "rn-pendo-sdk": "^3.1.1"
  },
  "devDependencies": {
    "@babel/core": "^7.21.4",
    "@babel/preset-env": "^7.21.4",
    "@babel/runtime": "^7.20.0",
    "@react-native/babel-preset": "^0.74.83",
    "@react-native/eslint-config": "^0.74.83",
    "@react-native/metro-config": "^0.74.83",
    "@react-native/typescript-config": "0.74.83",
    "@rnx-kit/align-deps": "^2.4.6",
    "@testing-library/jest-native": "^5.4.2",
    "@testing-library/react-native": "12.0.1",
    "@tsconfig/react-native": "^3.0.0",
    "@types/react": "^18.2.6",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.6.3",
    "detox": "^20.16.0",
    "eslint": "^8.19.0",
    "eslint-plugin-detox": "^1.0.0",
    "eslint-plugin-react": "^7.33.2",
    "eslint-plugin-react-native": "^4.0.0",
    "eslint-plugin-testing-library": "^5.11.0",
    "jest": "^29.7.0",
    "msw": "^1.2.1",
    "prettier": "^2.8.8",
    "react-test-renderer": "18.2.0",
    "typescript": "5.0.4"
  },
  "engines": {
    "node": ">=18"
  },
  "packageManager": "yarn@3.6.4"
}
```

Here's the CI setup - Its using latest macOS and latest cocoapods with Xcode version of 15.4 that is also what I have on my local env. 
```
name: ios deploy template

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      environment:
        type: string
        description: Environment to deploy to
        required: true

permissions:
  id-token: write
  contents: write

jobs:
  deployment:
    name: Deploy iOS to ${{ inputs.environment }}
    runs-on: macos-14
    environment: ${{ inputs.environment }}
    env:
        API_BASE_URL: ${{ vars.API_BASE_URL }}
        APPLE_ID: ${{ vars.APPLE_ID }}
        APP_PROVISIONING_PROFILE_NAME: ${{ vars.APP_PROVISIONING_PROFILE_NAME }}
        APP_STORE_API_KEY_P8: ${{ secrets.APP_STORE_API_KEY_P8 }}
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        ENV: ${{ vars.ENV }}
        ENV_NAME: ${{ vars.ENV_NAME }}
        ENV_NAMES: ${{ vars.ENV_NAMES }}
        FASTLANE_APPLE_PASS: ${{ secrets.FASTLANE_APPLE_PASS }}
        FASTLANE_ENV_NAME: ${{ vars.FASTLANE_ENV_NAME }}
        FASTLANE_ENV_FILE_NAME: ${{ vars.FASTLANE_ENV_FILE_NAME }}
        GITHUB_TOKEN: ${{ secrets.GH_BOT_PAT }}
        IOS_ENV_FILENAME: ${{ vars.IOS_ENV_FILENAME }}
        IOS_APP_NAME: ${{ vars.IOS_APP_NAME }}
        IS_OPERIX: ${{ vars.IS_OPERIX }}
        PENDO_API_KEY: ${{ secrets.PENDO_API_KEY }}
        SPLIT_ENVIRONMENT: ${{ vars.SPLIT_ENVIRONMENT }}
        SPLIT_IO_API_KEY: ${{ secrets.SPLIT_IO_API_KEY }}
        TEAM_ID: ${{ secrets.TEAM_ID }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup Xcode
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'

    - name: Setup Apple Certificates and Provisioning Profile
      env:
        BUILD_CERTIFICATE_P12_BASE64: '${{ secrets.BUILD_CERTIFICATE_P12_BASE64 }}'
        P12_PASSWORD: "${{ secrets.P12_PASSWORD }}"
        BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
        KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
      run: |
        # create variables

        CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
        PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
        KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

        # import certificate and provisioning profile from secrets
        echo -n "$BUILD_CERTIFICATE_P12_BASE64" | base64 --decode -o $CERTIFICATE_PATH
        echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

        # create temporary keychain
        security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
        security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
        security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

        # import certificate to keychain
        echo security import $CERTIFICATE_PATH -P password -A -v -t cert -f pkcs12 -k $KEYCHAIN_PATH 

        security -v import "$CERTIFICATE_PATH" -P $P12_PASSWORD -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
        security list-keychain -d user -s $KEYCHAIN_PATH

        # apply provisioning profile
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

    - name: Initialize Environment
      run: |
        source ./devops/ios/configure.sh && main ${{ inputs.environment }} 

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7.5'
        bundler-cache: false

    - name: Install CocoaPods
      run: gem install cocoapods

    - name: Clean Enviroment
      run: ./clean-all-ios.sh
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Deploy to App store
      run: |
        cd ./ios && bundle install
        bundle exec fastlane do_everything --env $FASTLANE_ENV_NAME --verbose

    - name: Set new build version envars
      run: source ./devops/ios/configure.sh && set_build_version_envs ${{ inputs.environment }}

    - uses: ifscore/devops-actions/tools/apply-branch-changes/v1@main
      with:
        branch: master
        files: | 
          ios/MobileApp dev-info.plist
          ios/MobileApp operixprod-info.plist
          ios/MobileApp operixprod-info.plist
          ios/MobileApp sageprod-info.plist
          ios/MobileApp.xcodeproj/project.pbxproj
          ios/MobileApp/Info.plist
          ios/MobileAppTests/Info.plist
          ios/fastlane/builds/${{ vars.FASTLANE_ENV_NAME }}.app.dSYM.zip
        GH_TOKEN: ${{ secrets.GH_BOT_PAT }}
        commit-message: "Updating iOS, ${{ vars.IOS_APP_NAME }} - Version ${{ env.IOS_APP_VERSION }}- iOS Build # ${{ env.IOS_BUILD_VERSION }} and clean"

    - name: Notify Slack
      uses: ifscore/devops-actions/notify/slack/v1@main
      with:
        channel-id: CLC00537D # scrum_team_mobile slack channel
        message: "${{ vars.IOS_APP_NAME }} - Version ${{ env.IOS_APP_VERSION }} - iOS Build # ${{ env.IOS_BUILD_VERSION }} Deployed to ${{ inputs.environment }}"
        slack-bot-token: ${{ secrets.SLACK_BOT_NOTIFY_TOKEN }}

```
